name = "diagnosis-game"
main = ".open-next/worker.js"
compatibility_date = "2026-02-16"
compatibility_flags = ["nodejs_compat"]
assets = { directory = ".open-next/assets", binding = "ASSETS" }
workers_dev = true
